forge 'http://forge.puppetlabs.com'

mod 'nginx', git: 'git://github.com/jfryman/puppet-nginx.git'
mod 'thomasvandoren/redis'
mod 'alup/rbenv'
mod 'stdlib', git: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
mod 'ghoneycutt/imagemagick'
mod 'saz/memcached'
