forge 'http://forge.puppetlabs.com'
mod 'nginx', git: 'git://github.com/jfryman/puppet-nginx.git'

mod 'rbenv', git: 'https://github.com/alup/puppet-rbenv.git'
mod 'stdlib', git: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
