Vagrant::Config.run do |config|
  config.vm.box = "puppet1204"

  config.vm.provision :puppet, :module_path => "./modules" do |puppet|
     puppet.manifests_path = "manifests"
     puppet.manifest_file  = "rails.pp"
  end
end
